project:
  type: website
  output-dir: _site

publish:
  method: gh-pages
  branch: gh-pages

website:
  title: "Strategies for infer from a huge collection of bibliometric data"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "PhD Thesis"
        contents:
          - href: index.qmd
          - href: about.qmd
          - href: database.qmd

      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
