---
title: Data base
---

## Data setup

> The data was extracted from the Scopus API containing the specific information of each author of a given article. This data is available at the following link:
>
> <https://drive.google.com/drive/folders/1pu2OTy7dH4BDjwIvc3LeF9PK8yZ75pJ4?usp=drive_link>

What do we consider to be the area of health in the [Scopus database](https://dev.elsevier.com/documentation/SCOPUSSearchAPI.wadl){style="color: gray"}?

| Code  | Description                                  |
|-------|----------------------------------------------|
| AGRI  | Agricultural and Biological Sciences         |
| BIOC  | Biochemistry, Genetics and Molecular Biology |
| DENT  | Dentistry                                    |
| HEAL  | Health Professions                           |
| IMMU  | Immunology and Microbiology                  |
| MEDI  | Medicine                                     |
| NEUR  | Neuroscience                                 |
| NURS  | Nursing                                      |
| PHAR  | Pharmacology, Toxicology and Pharmaceutics   |
| VETE  | Veterinary                                   |
| MULT  | Multidisciplinary                            |

**Time:** 2005 to 2021.

## Data dictionary

| Field               | Description                               |
|---------------------|-------------------------------------------|
| eid                 | Electronic ID                             |
| doi                 | Document Object Identifier                |
| pii                 | Publication Item Identifier               |
| pubmed-id           | MEDLINE Identifier                        |
| title               | Article Title                             |
| subtype             | Document Type code                        |
| subtypeDescription  | Document Type description                 |
| creator             | First Author (auth first entry)           |
| afid                | Affiliation ID                            |
| affilname           | Affiliation name                          |
| affiliation-city    | Affiliation city                          |
| affiliation-country | Affiliation country                       |
| author_count        | Author count                              |
| author_names        | Complete Author list (includes author ID) |
| author_ids          | Complete Author list (includes author ID) |
| author_afids        | Affiliation ID for each author            |
| coverDate           | Publication Date (YYYY-MM-DD)             |
| coverDisplayDate    | Publication Date (original text)          |
| publicationName     | Source Title                              |
| isbn                | Source Identifier                         |
| issn                | Source Identifier                         |
| aggregationType     | Source Type                               |
| volume              | Volume                                    |
| issueIdentifier     | Issue                                     |
| article-number      | Article Number                            |
| pageRange           | Page                                      |
| description         | Abstract                                  |
| authkeywords        | Author Keywords                           |
| citedby-count       | Cited-by Count                            |
| openaccess          | Open Access status                        |
| fund-acr            | Funding Agency Acronym                    |
| fund-no             | Funding Agency Identification             |
| fund-sponsor        | Funding Agency Name                       |

: Source: [Elsevier Developer Portal (2024)](https://dev.elsevier.com/sc_search_views.html){style="color: gray"}.
